//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exadel.CrazyPrice.Services.Mail.MailBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exadel.CrazyPrice.Services.Mail.MailBuilder.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///   &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body {
        ///         width: 100% !important;
        ///         -webkit-text-size-adjust: 100%;
        ///         -ms-text-size-adjust: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///      }
        ///
        ///      img {
        ///        outline: none;
        ///        text-decoration: none;
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///		d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CompanyMailBodyTemplateEn {
            get {
                return ResourceManager.GetString("CompanyMailBodyTemplateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///   &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body {
        ///         width: 100% !important;
        ///         -webkit-text-size-adjust: 100%;
        ///         -ms-text-size-adjust: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///      }
        ///
        ///      img {
        ///        outline: none;
        ///        text-decoration: none;
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///		d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CompanyMailBodyTemplateRu {
            get {
                return ResourceManager.GetString("CompanyMailBodyTemplateRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///   &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body {
        ///         width: 100% !important;
        ///         -webkit-text-size-adjust: 100%;
        ///         -ms-text-size-adjust: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///      }
        ///
        ///      img {
        ///        outline: none;
        ///        text-decoration: none;
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///		d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserMailBodyTemplateEn {
            get {
                return ResourceManager.GetString("UserMailBodyTemplateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///   &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body {
        ///         width: 100% !important;
        ///         -webkit-text-size-adjust: 100%;
        ///         -ms-text-size-adjust: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///      }
        ///
        ///      img {
        ///        outline: none;
        ///        text-decoration: none;
        ///        border: none;
        ///        -ms-interpolation-mode: bicubic;
        ///		d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserMailBodyTemplateRu {
            get {
                return ResourceManager.GetString("UserMailBodyTemplateRu", resourceCulture);
            }
        }
    }
}
